name: PolitiCraft
main: ch.haidar.politicraft.Plugin
version: 1.0
description: A politics plugin

commands:
  showPP:
    usage:  'Usage: /showPP'
    description: Shows the political power of user
  ppList:
    usage:  'Usage: /ppList'
    description: Shows citizens with the most pp
  createCountry:
    usage:  'Usage: /createCountry [countryName] [playerName]'
    description: creates country lol
  changePP:
    usage:  'Usage: /changePP [amount] [playerName]'
    description: changes pp of player if you want lol