name: PolitiCraft
main: ch.haidar.politicraft.Plugin
version: 1.0
description: A politics plugin

commands:
  showPP:
    usage:  'Usage: /showPP'
    description: Shows the political power of user
  PPList:
    usage:  'Usage: /ppList'
    description: Shows citizens with the most pp